# Path of helm-release file to skip during CI testing
skipList:
  - clusters/main/kubernetes/kube-system/cilium/app
  - clusters/main/kubernetes/system/longhorn/app
  - clusters/main/kubernetes/observability/exporter-fritz/app
  - clusters/main/kubernetes/apps/renovate/app
  - clusters/main/kubernetes/system/spegel/app
  - clusters/main/kubernetes/auth/authelia/app
  - clusters/main/kubernetes/core/clusterissuer/app
  - clusters/main/kubernetes/apps/actions-runners/app
  - clusters/main/kubernetes/apps/actions-runner-controller/app
  - clusters/main/kubernetes/apps/actions-runners-truecharts/app
dummyEnv:
  DOMAIN_0: base.dummy0.local
  DOMAIN_1: base.dummy1.local
  DOMAIN: dummy.local
  PODNET: 10.42.0.0/16
  METALLB_RANGE: 192.168.20.211-192.168.20.219
  NGINX_EXTERNAL_IP: 192.168.20.215
