name: clustertool-go-tests
on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
permissions:
  contents: read
jobs:

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.filter.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        with:
          list-files: json
          filters: |
            changed:
            - '**'

  build:
    runs-on:
      group: default    
    if: needs.check_changes.outputs.changes_detected == 'true'
    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - run:  |
          go build -o /usr/local/bin/clustertool
          go test -v ./... -race -covermode=atomic
          clustertool-dev
