name: clustertool-go-lint
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  pull_request:
    branches:
      - main
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'embed/**'
      - '!embed/generic/**'
      - 'pkg/**'
      - 'partial_builds/**'
      - 'pkg/**'
      - ".github/workflows/clustertool.test.yaml"
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on:
      group: default
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest
          args: >
            --timeout=3m
            --skip-dirs=embed/generic
            --enable-only=ineffassign,unused  # As a first start, can always add more linters later
