name: clustertool-go-tests
on:
  pull_request:
permissions:
  contents: read
jobs:

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.filter.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        with:
          list-files: json
          filters: |
            changed:
            - '**/*.go'

  build:
    needs: check_changes
    runs-on:
      group: default    
    if: needs.check_changes.outputs.changes_detected == 'true'
    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run:  |
          go build -o ./clustertool
          go test -v ./... -race -covermode=atomic
          ./clustertool info
