name: "Kubeconform"

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

env:
  KUBERNETES_DIR: ./embed/generic/kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478 # main
      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux kubeconform kustomize
      - name: Create dummy deploykey secret (CI only)
        shell: bash
        run: |
          SECRET_PATH="embed/generic/kubernetes/flux-system/flux-instance/app/deploy-key.sops.yaml"

          if [[ ! -f "$SECRET_PATH" ]]; then
            echo "Creating dummy deploy-key.sops.yaml for kubeconform"
            mkdir -p "$(dirname "$SECRET_PATH")"
            touch "$SECRET_PATH"
          fi
      - name: Run kubeconform
        shell: bash
        run: bash ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
